# testing
- hosts: localhost
  become: true

  pre_tasks:
    - name: update repositories on Ubuntu
      when: ansible_distribution == 'Ubuntu'
      apt: 
        update_cache: yes
      changed_when: False

    - name: update repositories on Arch
      when: ansible_distribution == 'Arch'
      pacman:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/01-packages.yml
    - include: tasks/02-environment.yml
