- name: Clone asdf repository
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "~{{user}}/.asdf"
    version: "v0.14.0"

- name: Add asdf plugins
  command: "~{{user}}/.asdf/bin/asdf plugin-add terraform"
  with_items:
    - neovim
    - golang
    - kubectl
    - helm
    - terraform

- name: Install asdf plugin
  command: "~{{user}}/.asdf/bin/asdf install terraform"
  become_user: "~{{user}}"
